apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataagent-backend
spec:
  replicas: 3  # 增加副本数提升吞吐
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4" 
            memory: "8Gi"
      - name: backend
        image: dataagent-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"

---
apiVersion: v1
kind: Service
metadata:
  name: dataagent-service
spec:
  selector:
    app: dataagent-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080