apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataagent-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dataagent
  template:
    metadata:
      labels:
        app: dataagent
    spec:
      containers:
      - name: backend
        image: dataagent-backend:latest
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        ports:
        - containerPort: 8000
      schedulerName: drf-scheduler  # 指定DRF调度器
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"

---
apiVersion: v1
kind: Service
metadata:
  name: dataagent-service
spec:
  selector:
    app: dataagent-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080